OBJS = App.o MatrixGraph.o ListGraph.o clock.o BiList.o MST.o ShortestPath.o Queue.o
OBJS += Additional.o
App: $(OBJS)
	g++ -o App $(OBJS)
App.o:
	g++ -c App.cpp
MatrixGraph.o:
	g++ -c MatrixGraph.cpp
ListGraph.o:
	g++ -c ListGraph.cpp
clock.o:
	g++ -c clock.cpp
BiList.o:
	g++ -c structures/BiList.cpp
MST.o:
	g++ -c MST.cpp
ShortestPath.o:
	g++ -c ShortestPath.cpp
Queue.o:
	g++ -c structures/Queue.cpp
Additional.o:
	g++ -c structures/Additional.cpp

clean:
	rm -f core App $(OBJS)